url <- read_html("http://www.basketball-reference.com/leagues/NBA_2004_games.html")
tbl <- html_table(url)
dat <- tbl_df(as.data.frame(tbl[1]))
url1 <- read_html("http://www.basketball-reference.com/leagues/NBA_2005_games.html")
tbl1 <- html_table(url1)
dat1 <- tbl_df(as.data.frame(tbl1[1]))
url2 <- read_html("http://www.basketball-reference.com/leagues/NBA_2006_games.html")
tbl2 <- html_table(url2)
dat2 <- tbl_df(as.data.frame(tbl2[1]))
url3 <- read_html("http://www.basketball-reference.com/leagues/NBA_2007_games.html")
tbl3 <- html_table(url3)
dat3 <- tbl_df(as.data.frame(tbl3[1]))
url4 <- read_html("http://www.basketball-reference.com/leagues/NBA_2008_games.html")
tbl4 <- html_table(url4)
dat4 <- tbl_df(as.data.frame(tbl4[1]))
url5 <- read_html("http://www.basketball-reference.com/leagues/NBA_2009_games.html")
tbl5 <- html_table(url5)
dat5 <- tbl_df(as.data.frame(tbl5[1]))
url6 <- read_html("http://www.basketball-reference.com/leagues/NBA_2010_games.html")
tbl6 <- html_table(url6)
dat6 <- tbl_df(as.data.frame(tbl6[1]))
url7 <- read_html("http://www.basketball-reference.com/leagues/NBA_2011_games.html")
tbl7 <- html_table(url7)
dat7 <- tbl_df(as.data.frame(tbl7[1]))
url8 <- read_html("http://www.basketball-reference.com/leagues/NBA_2012_games.html")
tbl8 <- html_table(url8)
dat8 <- tbl_df(as.data.frame(tbl8[1]))
url9 <- read_html("http://www.basketball-reference.com/leagues/NBA_2013_games.html")
tbl9 <- html_table(url9)
dat9 <- tbl_df(as.data.frame(tbl9[1]))
url10 <- read_html("http://www.basketball-reference.com/leagues/NBA_2014_games.html")
tbl10 <- html_table(url10)
dat10 <- tbl_df(as.data.frame(tbl10[1]))
url11 <- read_html("http://www.basketball-reference.com/leagues/NBA_2015_games.html")
tbl11 <- html_table(url11)
dat11 <- tbl_df(as.data.frame(tbl11[1]))

d1 <- rbind(dat, dat1, dat2, dat3, dat4, dat5, dat6, dat7, dat8, dat9, dat10)
names(d1) <- c("Date", "ET.Start", "Var.3", "VisitingTeam", "PTS.V", "HomeTeam", "PTS.H", "Var.8", "Notes")
d1$h.diff <- d1$PTS.H - d1$PTS.V
d1$v.diff <- d1$PTS.V - d1$PTS.H
d1$game.id <- seq(1, nrow(d1), 1)
# d1$outcome <- ifelse()
# home <- d1 %>% filter(HomeTeam == "Boston Celtics")
# visiting <- d1 %>% filter(VisitingTeam == "Boston Celtics")
# 
# home$score.dif <- home$PTS.H - home$PTS.V #negative values denote celtics' loss
# visiting$score.dif <- visiting$PTS.V - visiting$PTS.H
# kable(head(home)) # display table

url14 <- read_html("http://www.basketball-reference.com/leagues/NBA_2014_games.html")
tbl14 <- html_table(url14)

d14 <- tbl_df(as.data.frame(tbl14[1]))